'use strict';

/*
 * Apache generator — .htaccess / server-config User-Agent blocking using
 * mod_rewrite with one carefully escaped, case-insensitive RewriteCond and a
 * plain 403 RewriteRule. Safe: no unescaped regex, no contradictory rules.
 */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory(require);
  else {
    const BB = root.BB = root.BB || {};
    BB.apacheGenerator = factory(name => {
      const key = name.replace(/^\.\//, '');
      if (!BB[key]) throw new Error('botblocker module missing: ' + name);
      return BB[key];
    });
  }
})(typeof self !== 'undefined' ? self : globalThis, function (require) {

  const { tokenBoundaryPattern, regexEscape } = require('./botPatternMatcher');

  function generate(tokens, options) {
    const opts = options || {};
    const list = (tokens || []).slice().sort((a, b) => a.localeCompare(b));
    if (!list.length) {
      return {
        text: '# No blocked crawlers selected — nothing to generate for Apache.\n',
        valid: true, placement: [], empty: true
      };
    }
    const lines = [];
    lines.push('# Generated by huvanti — AI Crawler & LLM Bot Blocker');
    lines.push('# Technical blocking: these rules return 403 at server level.');
    lines.push('# User-Agent values can be spoofed — combine with IP verification for stronger guarantees.');
    lines.push('');
    lines.push('<IfModule mod_rewrite.c>');
    lines.push('RewriteEngine On');
    lines.push('RewriteCond %{HTTP_USER_AGENT} ' + tokenBoundaryPattern(list) + ' [NC]');
    lines.push('RewriteRule ^ - [F,L]');
    lines.push('</IfModule>');
    lines.push('');
    lines.push('# Alternative without mod_rewrite (mod_setenvif + Apache 2.4 Require):');
    for (const t of list.slice(0, 40)) {
      lines.push('# BrowserMatchNoCase "^' + regexEscape(t) + '" ai_bot=1');
    }
    lines.push('# <RequireAny>');
    lines.push('#   Require all granted');
    lines.push('#   Require not env ai_bot');
    lines.push('# </RequireAny>');
    const placement = [
      'For per-directory control, save as .htaccess in your site root (requires AllowOverride to permit mod_rewrite).',
      'For best performance, place the rules directly in your <VirtualHost>/<Directory> block instead of .htaccess.',
      'Test with `apachectl configtest` (or `apache2ctl configtest`) before reloading Apache.'
    ];
    if (opts.rateLimit && opts.rateLimit.enabled) {
      lines.push('');
      lines.push('# Optional rate control: mod_ratelimit or mod_reqtimeout examples (server config, not .htaccess):');
      lines.push('# <IfModule mod_headers.c>');
      lines.push('#   Header always set Retry-After "60" env=RATE_LIMITED');
      lines.push('# </IfModule>');
      lines.push('# Real per-client rate limiting in Apache is typically done with mod_security,');
      lines.push('# mod_ratelimit (bandwidth) or an upstream CDN/WAF — review options for your stack.');
      placement.push('Rate limiting in Apache depends on modules and version — the generated notes are guidance, not a drop-in config.');
    }
    lines.push('');
    return { text: lines.join('\n'), valid: true, placement };
  }

  return { generate };
});
