'use strict';

/*
 * Cloudflare generator — produces a WAF custom rule expression plus clearly
 * separated deployment guidance. Does NOT invent features or claim plan
 * support; every capability note is phrased so the user verifies in their
 * own dashboard/plan.
 */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory(require);
  else {
    const BB = root.BB = root.BB || {};
    BB.cloudflareGenerator = factory(name => {
      const key = name.replace(/^\.\//, '');
      if (!BB[key]) throw new Error('botblocker module missing: ' + name);
      return BB[key];
    });
  }
})(typeof self !== 'undefined' ? self : globalThis, function (require) {

  function generate(tokens, options) {
    const opts = options || {};
    const list = (tokens || []).slice().sort((a, b) => a.localeCompare(b));
    if (!list.length) {
      return {
        expression: '',
        text: '# No blocked crawlers selected — nothing to generate for Cloudflare.\n',
        guidance: [], empty: true
      };
    }
    // Cloudflare rules language: http.user_agent contains "Token"
    const clauses = list.map(t => 'http.user_agent contains "' + String(t).replace(/"/g, '\\"') + '"');
    const expression = '(' + clauses.join('\n     or ') + ')';

    const guidance = [
      'Open your Cloudflare dashboard → the Security section → WAF → Custom rules (the exact navigation and the number of rules available depend on your Cloudflare plan — check your plan\u2019s limits).',
      'Create a new custom rule, switch the expression to the expression editor, paste the expression above, set the action (Block, or Managed Challenge if you prefer friction over hard rejection) and deploy.',
      'Verify the rule fires by testing with a spoofed User-Agent against your site, then check Security Events for matches.',
      'Token-boundary limitation: Cloudflare\u2019s `contains` is substring matching. Substring matches cannot exclude similarly named bots (for example an expression for "Applebot" also matches "Applebot-Extended"). If you need to allow one and block the other, use exact matching operators on the full User-Agent or rely on the nginx/Apache/middleware rules which use token boundaries.',
      'Cloudflare also offers AI-crawler controls (for example blocking known AI bots and Verified Bot handling in the bot management settings). Availability depends on plan and current dashboard — verify before relying on it.',
      'Rule expression ≠ deployment: the expression above is only the matching logic; the deployment steps above are how you apply it.'
    ];

    const lines = [];
    lines.push('# Generated by huvanti — AI Crawler & LLM Bot Blocker');
    lines.push('# Cloudflare WAF custom rule expression (Security → WAF → Custom rules → Expression editor):');
    lines.push('');
    lines.push(expression);
    lines.push('');
    lines.push('# Suggested rule name: "Block selected AI crawlers"');
    lines.push('# Suggested action: Block (or Managed Challenge)');
    lines.push('#');
    lines.push('# Deployment guidance (verify in your dashboard — features vary by plan):');
    for (const g of guidance) lines.push('#   • ' + g);
    if (opts.rateLimit && opts.rateLimit.enabled) {
      lines.push('#');
      lines.push('# Rate control: Cloudflare rate limiting rules are configured separately (Security → WAF → Rate limiting rules).');
      lines.push('# A request-per-period threshold of roughly ' + (opts.rateLimit.requestsPerMinute || 60) + ' requests/minute matches your selection, but the right value depends on your traffic — review before enabling.');
    }
    lines.push('');
    return { expression, text: lines.join('\n'), guidance, empty: false };
  }

  return { generate };
});
