'use strict';

/*
 * Generic middleware generator — Node.js (plain http + Express), PHP and
 * Laravel snippets that inspect the User-Agent with token-boundary matching
 * and return 403 Forbidden for blocked bots. All snippets state clearly that
 * User-Agent values can be spoofed.
 */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory(require);
  else {
    const BB = root.BB = root.BB || {};
    BB.middlewareGenerator = factory(name => {
      const key = name.replace(/^\.\//, '');
      if (!BB[key]) throw new Error('botblocker module missing: ' + name);
      return BB[key];
    });
  }
})(typeof self !== 'undefined' ? self : globalThis, function (require) {

  const { regexEscape } = require('./botPatternMatcher');

  const HEADER = [
    '// Generated by huvanti — AI Crawler & LLM Bot Blocker',
    '// Technical blocking: returns 403 at application level.',
    '// User-Agent values can be spoofed — combine with IP verification for stronger guarantees.'
  ];

  function jsList(tokens) {
    return (tokens || []).map(t => "'" + String(t).replace(/'/g, "\\'") + "'").sort();
  }
  function phpList(tokens) {
    return (tokens || []).map(t => "'" + String(t).replace(/'/g, "\\'") + "'").sort();
  }

  function generateNode(tokens) {
    const list = jsList(tokens);
    if (!list.length) return '// No blocked crawlers selected — nothing to generate.\n';
    return HEADER.concat([
      '// Express middleware (plain Node http: use the same isBlockedBot() on req.headers["user-agent"])',
      '',
      'const AI_BLOCKED_TOKENS = new Set([' + list.join(', ') + ']);',
      '',
      'function isBlockedBot(userAgent) {',
      '  const ua = String(userAgent || "");',
      '  for (const token of AI_BLOCKED_TOKENS) {',
      '    const i = ua.indexOf(token);',
      '    if (i === -1) continue;',
      '    const boundary = /[A-Za-z0-9_-]/;',
      '    const before = i > 0 ? ua[i - 1] : "";',
      '    const after = ua[i + token.length] || "";',
      '    if (!boundary.test(before) && !boundary.test(after)) return true; // exact product token',
      '  }',
      '  return false;',
      '}',
      '',
      'app.use(function aiBotBlocker(req, res, next) {',
      '  if (isBlockedBot(req.headers["user-agent"])) {',
      '    return res.status(403).send("Forbidden");',
      '  }',
      '  next();',
      '});',
      ''
    ]).join('\n');
  }

  function generatePhp(tokens) {
    const list = phpList(tokens);
    if (!list.length) return '<?php // No blocked crawlers selected — nothing to generate.';
    return ['<?php'].concat(HEADER.map(l => '// ' + l.replace(/^\/\/ ?/, '')), [
      '// Plain PHP — include at the top of your entry script (e.g. index.php).',
      '',
      'function aiBotBlocker_isBlocked(string $userAgent, array $tokens): bool {',
      '  foreach ($tokens as $token) {',
      '    $pos = strpos($userAgent, $token);',
      '    while ($pos !== false) {',
      '      $before = $pos > 0 ? $userAgent[$pos - 1] : "";',
      '      $after  = $userAgent[$pos + strlen($token)] ?? "";',
      '      $isBoundary = fn($c) => $c !== "" && preg_match("/[A-Za-z0-9_-]/", $c);',
      '      if (!$isBoundary($before) && !$isBoundary($after)) {',
      '        return true; // exact product token match',
      '      }',
      '      $pos = strpos($userAgent, $token, $pos + 1);',
      '    }',
      '  }',
      '  return false;',
      '}',
      '',
      '$aiBlockedTokens = [' + list.join(', ') + '];',
      '',
      'if (aiBotBlocker_isBlocked($_SERVER["HTTP_USER_AGENT"] ?? "", $aiBlockedTokens)) {',
      '  http_response_code(403);',
      '  exit("Forbidden");',
      '}',
      ''
    ]).join('\n');
  }

  function generateLaravel(tokens) {
    const list = phpList(tokens);
    if (!list.length) return '<?php // No blocked crawlers selected — nothing to generate.';
    return ['<?php'].concat(HEADER.map(l => '// ' + l.replace(/^\/\/ ?/, '')), [
      '',
      'namespace App\\Http\\Middleware;',
      '',
      'use Closure;',
      'use Illuminate\\Http\\Request;',
      '',
      'class BlockAiBots',
      '{',
      '    // User-Agent values can be spoofed — combine with IP verification for stronger guarantees.',
      '    private const BLOCKED_TOKENS = [',
      list.map(t => '        ' + t + ',').join('\n'),
      '    ];',
      '',
      '    public function handle(Request $request, Closure $next)',
      '    {',
      '        $ua = (string) $request->userAgent();',
      '        foreach (self::BLOCKED_TOKENS as $token) {',
      '            $pos = strpos($ua, $token);',
      '            while ($pos !== false) {',
      '                $before = $pos > 0 ? $ua[$pos - 1] : "";',
      '                $after  = $ua[$pos + strlen($token)] ?? "";',
      '                $isBoundary = static function (string $c): bool {',
      '                    return $c !== "" && preg_match(\'/[A-Za-z0-9_-]/\', $c) === 1;',
      '                };',
      '                if (!$isBoundary($before) && !$isBoundary($after)) {',
      '                    abort(403, \'Forbidden\');',
      '                }',
      '                $pos = strpos($ua, $token, $pos + 1);',
      '            }',
      '        }',
      '',
      '        return $next($request);',
      '    }',
      '}',
      '',
      '// Register in bootstrap/app.php (Laravel 11+) or app/Http/Kernel.php (older versions):',
      '//   $middleware->append(\\App\\Http\\Middleware\\BlockAiBots::class);',
      '// Rate limiting: define a named rate limiter in AppServiceProvider::boot() (RateLimiter::for)',
      '// and apply it to routes — tune limits to your traffic.',
      ''
    ]).join('\n');
  }


  function generate(tokens, options) {
    const opts = options || {};
    return {
      node: generateNode(tokens),
      php: generatePhp(tokens),
      laravel: generateLaravel(tokens)
    };
  }

  return { generate, generateNode, generatePhp, generateLaravel, HEADER };
});
