'use strict';

/*
 * Nginx generator, robust map-based User-Agent blocking (no unsafe `if`
 * pattern-spam). One map in the http{} context + a single guarded `if` (the
 * documented safe use inside server/location) returning 403.
 */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory(require);
  else {
    const BB = root.BB = root.BB || {};
    BB.nginxGenerator = factory(name => {
      const key = name.replace(/^\.\//, '');
      if (!BB[key]) throw new Error('botblocker module missing: ' + name);
      return BB[key];
    });
  }
})(typeof self !== 'undefined' ? self : globalThis, function (require) {

  const { tokenBoundaryPattern } = require('./botPatternMatcher');

  function chunk(tokens, size) {
    const out = [];
    for (let i = 0; i < tokens.length; i += size) out.push(tokens.slice(i, i + size));
    return out;
  }

  function generate(tokens, options) {
    const opts = options || {};
    const list = (tokens || []).slice().sort((a, b) => a.localeCompare(b));
    if (!list.length) {
      return {
        text: '# No blocked crawlers selected, nothing to generate for nginx.\n',
        valid: true, placement: [], empty: true
      };
    }
    const lines = [];
    lines.push('# Generated by huvanti: AI Crawler & LLM Bot Blocker');
    lines.push('# Technical blocking: these rules reject requests at server level (403).');
    lines.push('# User-Agent values can be spoofed, combine with IP verification for stronger guarantees.');
    lines.push('');
    lines.push('# ── 1) Put this map in the http{} context ─────────────────────────────');
    lines.push('# (e.g. /etc/nginx/conf.d/ai-bots.map.conf on Debian/Ubuntu, included by nginx.conf)');
    lines.push('map $http_user_agent $ai_bot_blocked {');
    lines.push('    default 0;');
    // Split long alternations across a few map entries for readability.
    for (const part of chunk(list, 6)) {
      const pattern = tokenBoundaryPattern(part);
      lines.push('    ~*' + pattern + '  1;');
    }
    lines.push('}');
    lines.push('');
    lines.push('# ── 2) Apply inside your server{} block (or a location) ────────────────');
    lines.push('# This is the documented safe use of if: a single return, no rewrite side effects.');
    lines.push('if ($ai_bot_blocked) {');
    lines.push('    return 403;');
    lines.push('}');
    const placement = [
      'Add the map to the http{} context (a separate conf.d include file is cleanest), maps cannot go inside server{}.',
      'Add the if-block inside the server{} (or a specific location{}) that serves your site.',
      'Validate with `nginx -t`, then reload with `systemctl reload nginx` (or `nginx -s reload`).'
    ];
    if (opts.rateLimit && opts.rateLimit.enabled) {
      const rps = opts.rateLimit.requestsPerSecond || 1;
      const burst = opts.rateLimit.burst || 10;
      lines.push('');
      lines.push('# ── Optional: rate control for AI traffic (recommendation, tune to your traffic) ──');
      lines.push('# http{} context:');
      lines.push('# limit_req_zone $binary_remote_addr zone=ai_crawl_rate:10m rate=' + rps + 'r/s;');
      lines.push('# server/location context:');
      lines.push('# limit_req zone=ai_crawl_rate burst=' + burst + ' nodelay;');
      lines.push('# Note: limit_req counts per client IP for ALL requests to that location, not only AI bots.');
      lines.push('# To rate-limit only AI crawlers, map $ai_bot_blocked into a key (e.g. map with $binary_remote_addr) and use that zone key.');
      placement.push('Rate limiting values are recommendations, review them against your real traffic before deploying.');
    }
    lines.push('');
    return { text: lines.join('\n'), valid: true, placement };
  }

  return { generate };
});
