'use strict';

/*
 * robots.txt generator, builds a valid, non-contradictory advisory file from
 * the resolved configuration. Ordering is deterministic. The file always
 * carries a comment clarifying it is advisory (crawler-cooperation), not
 * technical access control.
 */
(function (root, factory) {
  if (typeof module === 'object' && module.exports) module.exports = factory(require);
  else {
    const BB = root.BB = root.BB || {};
    BB.robotsGenerator = factory(name => {
      const key = name.replace(/^\.\//, '');
      if (!BB[key]) throw new Error('botblocker module missing: ' + name);
      return BB[key];
    });
  }
})(typeof self !== 'undefined' ? self : globalThis, function (require) {

  const classifier = require('./botClassifier');
  const db = require('./botDatabase');

  const MAX_GROUPS = 200;

  function normalizePaths(list) {
    const seen = new Set();
    const out = [];
    for (let raw of (list || [])) {
      let p = String(raw || '').trim();
      if (!p) continue;
      if (!p.startsWith('/')) p = '/' + p;
      if (!/[^\w.+~/-]/.test(p) && p.length <= 500 && !seen.has(p)) { seen.add(p); out.push(p); }
    }
    return out.sort();
  }

  function generate(config, resolved, meta) {
    const mode = config.mode || 'block-all';
    const modeInfo = classifier.MODES.find(m => m.id === mode) || classifier.MODES[0];
    const paths = config.paths || {};
    const blockTargets = paths.mode === 'specific' ? normalizePaths(paths.list) : ['/'];
    const exceptions = (config.exceptions && config.exceptions.enabled) ? normalizePaths(config.exceptions.list) : [];
    const defaultGroup = config.defaultGroup || 'allow';
    const notes = [];
    const lines = [];

    lines.push('# robots.txt generated by huvanti: AI Crawler & LLM Bot Blocker');
    if (meta && meta.website) lines.push('# Website: ' + meta.website);
    lines.push('# Protection mode: ' + modeInfo.label + ' · database v' + db.DB_VERSION + ' (' + db.DB_UPDATED + ')');
    lines.push('# Advisory control: robots.txt asks compliant crawlers not to access these paths.');
    lines.push('# It does not enforce access control, for stronger enforcement use the server/CDN-level rules this tool generates.');
    lines.push('');

    const blocked = resolved.filter(r => r.effective === 'block');
    const allowed = resolved.filter(r => r.effective === 'allow');
    const wildcardBlocksAll = defaultGroup === 'block-others';
    const wildcardMirrors = defaultGroup === 'mirror' && blockTargets.length && blockTargets[0] !== '/';

    function group(agent, ruleLines) {
      lines.push('User-agent: ' + agent);
      for (const l of ruleLines) lines.push(l);
      lines.push('');
    }

    // 1) Blocked bots, explicit groups
    for (const r of blocked) {
      const rules = [];
      if (blockTargets[0] === '/') rules.push('Disallow: /');
      else for (const p of blockTargets) rules.push('Disallow: ' + p);
      for (const a of exceptions) rules.push('Allow: ' + a);
      group(r.bot.token, rules);
      if (r.bot.robotsSupport === 'documented-no' || r.bot.robotsSupport === 'reported-mixed' || r.bot.robotsSupport === 'unknown') {
        notes.push({ level: 'warning', bot: r.bot.name, message: r.bot.name + ' is not documented to reliably follow robots.txt (support: ' + r.bot.robotsSupport + '). Server/CDN-level rules are the only dependable control for it.' });
      }
      if (r.bot.id === 'google-extended' || r.bot.id === 'applebot-extended' || r.bot.id === 'google-cloudvertexbot') {
        notes.push({ level: 'info', bot: r.bot.name, message: r.bot.name + ' is a usage-control token, not a crawler, this rule changes how already-crawled data may be used; it does not stop the operator\u2019s main crawler.' });
      }
    }
    if (blocked.length > MAX_GROUPS) {
      notes.push({ level: 'warning', message: 'More than ' + MAX_GROUPS + ' bot groups requested, output truncated. Large robots.txt files may exceed crawler size limits (500 KiB).' });
    }

    // 2) Explicitly allowed bots, only when the allow is meaningful
    const allowGroupsMatter = wildcardBlocksAll || mode === 'allow-selected' || mode === 'allow-all' ||
      ['block-training', 'block-search', 'block-extraction'].includes(mode);
    if (allowGroupsMatter) {
      for (const r of allowed.slice(0, MAX_GROUPS)) {
        group(r.bot.token, ['Allow: /']);
      }
    }

    // 3) Default group
    if (defaultGroup === 'allow') {
      group('*', ['Allow: /']);
    } else if (wildcardBlocksAll) {
      const rules = ['Disallow: /'].concat(exceptions.map(a => 'Allow: ' + a));
      group('*', rules);
      notes.push({ level: 'warning', message: 'The wildcard group is set to Disallow: /, this asks ALL compliant crawlers (including Googlebot, Bingbot and other search engines) not to crawl your site. This is rarely intended; consider per-bot groups instead.' });
    } else if (wildcardMirrors) {
      group('*', blockTargets.map(p => 'Disallow: ' + p));
    } else if (defaultGroup === 'none') {
      lines.push('# (No User-agent: * group, unspecified crawlers are allowed by default.)');
      lines.push('');
    }

    // 4) Sitemap
    if (config.sitemap) {
      lines.push('Sitemap: ' + config.sitemap);
      lines.push('');
    }

    return { text: lines.join('\n').replace(/\n{3,}$/g, '\n'), notes };
  }

  return { generate, normalizePaths };
});
