'use strict';
const { crawlSite } = require('./crawler');
const { analyzeSitemap } = require('./sitemapAnalyzer');
const buckets=new Map(); let inflight=0; const MAX_INFLIGHT=2, WINDOW_MS=10*60*1000, MAX_PER_WINDOW=8, SCAN_MS=120000;
function clientIp(req){return String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim();}
function rateOk(ip){const now=Date.now(); const arr=(buckets.get(ip)||[]).filter(t=>now-t<WINDOW_MS); if(arr.length>=MAX_PER_WINDOW){buckets.set(ip,arr);return false;} arr.push(now); buckets.set(ip,arr); return true;}
function send(res,event,data){try{res.write('event: '+event+'\n');res.write('data: '+JSON.stringify(data)+'\n\n');}catch{}}
function opts(body, ac, onProgress){ return { signal:ac.signal, onProgress, maxUrls:body.maxUrls, depth:body.depth, includeSubdomains:!!body.includeSubdomains, includeNoindex:!!body.includeNoindex, includeImages:!!body.includeImages, changefreq:body.changefreq||'', concurrency:6 }; }
async function handle(req,res,body){ const ip=clientIp(req); if(!rateOk(ip)){res.statusCode=429;res.setHeader('content-type','application/json');res.end(JSON.stringify({code:'ratelimit',message:'Too many sitemap jobs. Please wait a few minutes.'}));return;} if(inflight>=MAX_INFLIGHT){res.statusCode=503;res.setHeader('content-type','application/json');res.end(JSON.stringify({code:'busy',message:'The sitemap crawler is busy. Please try again shortly.'}));return;} res.writeHead(200,{'Content-Type':'text/event-stream; charset=utf-8','Cache-Control':'no-cache, no-store','Connection':'keep-alive','X-Accel-Buffering':'no'}); const ac=new AbortController(); const timer=setTimeout(()=>ac.abort(),SCAN_MS); req.on('close',()=>ac.abort()); inflight++; try{ const mode=body.mode==='analyze'?'analyze':'generate'; const fn=mode==='analyze'?analyzeSitemap:crawlSite; const report=await fn(String(body.url||''), opts(body, ac, s=>send(res,'progress',s))); send(res,'result',report);}catch(e){send(res,'error',{code:e.code||(ac.signal.aborted?'cancelled':'error'),message:e.message||'Unable to complete crawl',validation:e.validation||e.validationErrors});}finally{inflight--;clearTimeout(timer);res.end();}}
module.exports={handle};
