'use strict';
const { validateUrl } = require('./urlValidator');
const { readSitemap, extractLocs } = require('./sitemapDiscovery');
const { safeFetch } = require('./safeFetcher');
const { parsePage } = require('./pageParser');
const { analyzeIndexability } = require('./indexabilityAnalyzer');
const { canonicalDecision } = require('./canonicalAnalyzer');
const { canonicalKey, isInternal } = require('./urlNormalizer');
const { validateXml } = require('./sitemapValidator');
async function analyzeSitemap(raw, opts={}) {
  const started=Date.now(); const input=await validateUrl(raw); const sm=await readSitemap(input.toString(), opts); const xml=sm.xml||''; const structure=validateXml(xml, sm.isIndex?'index':'urlset'); let locs=extractLocs(xml, input.toString()); const indexChildren = sm.isIndex ? locs.slice(0, 20) : []; if (sm.isIndex) { const childUrls=[]; for (const child of indexChildren) { try { const c = await readSitemap(child, opts); if (c.valid && !c.isIndex) childUrls.push(...c.urls); } catch (e) {} if (childUrls.length >= (opts.maxUrls||500)) break; } locs = childUrls.length ? childUrls : locs; } const rows=[]; const seen=new Set(); const max=Math.min(locs.length, opts.maxUrls||500);
  for(let i=0;i<max;i++){ const url=locs[i]; let row={url,status:null,indexable:false,canonical:'',included:false,reason:''}; try{ const r=await safeFetch(url,{...opts,maxBytes:650*1024}); row.status=r.status; row.finalUrl=r.finalUrl; const parsed=parsePage(r.body,r.finalUrl); Object.assign(row,{noindex:parsed.noindex, canonical:parsed.canonical||r.finalUrl, headers:r.headers}); const ix=analyzeIndexability(row,opts); const cd=canonicalDecision(row,input.toString(),true); const dup=seen.has(canonicalKey(cd.canonical||url)); if(dup){ row.reason='Excluded: Duplicate URL'; } else if(cd.canonicalized){ row.reason=cd.reason; } else { row.reason=ix.reason; row.included=ix.indexable; } seen.add(canonicalKey(cd.canonical||url)); row.indexable=ix.indexable&&!cd.canonicalized&&!dup; if(!isInternal(url,input.toString(),true)) { row.reason='Excluded: External domain'; row.indexable=false; row.included=false; } }catch(e){ row.reason=e.code==='timeout'?'Timeout':(e.message||'Fetch failed'); } rows.push(row); if(opts.onProgress) opts.onProgress({stage:'analyze', message:`${i+1} sitemap URLs checked`, discovered:locs.length, crawled:i+1}); }
  const broken=rows.filter(r=>r.status===404||r.status===410||r.status>=500).length; const redirects=rows.filter(r=>r.status>=300&&r.status<400).length; const duplicates=rows.filter(r=>/Duplicate/.test(r.reason)).length; const nonIndexable=rows.filter(r=>!r.indexable).length; let score=100; if(!structure.valid) score-=35; score-=Math.min(35, Math.round((broken/Math.max(1,rows.length))*100)); score-=Math.min(15, Math.round((redirects/Math.max(1,rows.length))*60)); score-=Math.min(15, Math.round((duplicates/Math.max(1,rows.length))*60)); score-=Math.min(20, Math.round((nonIndexable/Math.max(1,rows.length))*30)); score=Math.max(0,score);
  return { mode:'analyze', input:input.toString(), sitemap:sm.url, xmlValid:structure.valid, xmlErrors:structure.errors, healthScore:score, urls:rows, stats:{ urlCount:locs.length, sitemapIndexChildren:indexChildren.length, checked:rows.length, broken, redirects, duplicates, nonIndexable, missingLastmod:(xml.match(/<url>/g)||[]).length-(xml.match(/<lastmod>/g)||[]).length, generationTimeMs:Date.now()-started } };
}
module.exports={analyzeSitemap};
