'use strict';

/*
 * TLD intelligence — curated registry database.
 * For each TLD: registry operator, type (gTLD/ccTLD), RDAP base endpoint,
 * IANA-assigned WHOIS server and IDN support where known.
 *
 * This is a maintained local snapshot of IANA registry data. Entries are only
 * included when the registry/endpoint is well-established; unknown TLDs are
 * reported as "not in local database" — never guessed.
 */

const T = {
  // { registry, type: 'g'|'cc', rdap, whois, idn: true|false|null, country }
  com: { registry: 'Verisign, Inc.', type: 'g', rdap: 'https://rdap.verisign.com/com/v1/', whois: 'whois.verisign-grs.com', idn: false },
  net: { registry: 'Verisign, Inc.', type: 'g', rdap: 'https://rdap.verisign.com/net/v1/', whois: 'whois.verisign-grs.com', idn: false },
  org: { registry: 'Public Interest Registry (PIR)', type: 'g', rdap: 'https://rdap.publicinterestregistry.org/rdap/', whois: 'whois.pir.org', idn: true },
  info: { registry: 'Identity Digital', type: 'g', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.identitydigital.services', idn: true },
  biz: { registry: 'Identity Digital', type: 'g', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.identitydigital.services', idn: true },
  mobi: { registry: 'Identity Digital', type: 'g', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.identitydigital.services', idn: true },
  pro: { registry: 'Identity Digital', type: 'g', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.identitydigital.services', idn: true },
  name: { registry: 'Identity Digital', type: 'g', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.identitydigital.services', idn: true },
  asia: { registry: 'Identity Digital', type: 'g', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.identitydigital.services', idn: true },
  xyz: { registry: 'XYZ.com LLC', type: 'g', rdap: 'https://rdap.centralnic.com/xyz/', whois: 'whois.nic.xyz', idn: true },
  site: { registry: 'Radix', type: 'g', rdap: 'https://rdap.centralnic.com/site/', whois: 'whois.nic.site', idn: true },
  online: { registry: 'Radix', type: 'g', rdap: 'https://rdap.centralnic.com/online/', whois: 'whois.nic.online', idn: true },
  tech: { registry: 'Radix', type: 'g', rdap: 'https://rdap.centralnic.com/tech/', whois: 'whois.nic.tech', idn: true },
  store: { registry: 'Radix', type: 'g', rdap: 'https://rdap.centralnic.com/store/', whois: 'whois.nic.store', idn: true },
  shop: { registry: 'GMO Registry', type: 'g', rdap: 'https://rdap.gmoregistry.net/rdap/', whois: 'whois.nic.shop', idn: true },
  app: { registry: 'Google Registry', type: 'g', rdap: 'https://rdap.nic.google/', whois: 'whois.nic.google', idn: true },
  dev: { registry: 'Google Registry', type: 'g', rdap: 'https://rdap.nic.google/', whois: 'whois.nic.google', idn: true },
  page: { registry: 'Google Registry', type: 'g', rdap: 'https://rdap.nic.google/', whois: 'whois.nic.google', idn: true },
  blog: { registry: 'Automattic (Knock Knock WHOIS There)', type: 'g', rdap: 'https://rdap.centralnic.com/blog/', whois: 'whois.nic.blog', idn: true },
  cloud: { registry: 'Aruba PEC', type: 'g', rdap: 'https://rdap.nic.cloud/rdap/', whois: 'whois.nic.cloud', idn: true },
  club: { registry: 'CLUB Domains', type: 'g', rdap: 'https://rdap.nic.club/', whois: 'whois.nic.club', idn: true },
  design: { registry: 'Registry Services, LLC', type: 'g', rdap: 'https://rdap.centralnic.com/design/', whois: 'whois.nic.design', idn: true },
  digital: { registry: 'Identity Digital', type: 'g', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.identitydigital.services', idn: true },
  io: { registry: 'Internet Computer Bureau (Identity Digital)', type: 'cc', country: 'British Indian Ocean Territory', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.nic.io', idn: true },
  co: { registry: 'GoDaddy Registry (.CO Internet)', type: 'cc', country: 'Colombia', rdap: 'https://rdap.nic.co/', whois: 'whois.nic.co', idn: true },
  ai: { registry: 'Government of Anguilla', type: 'cc', country: 'Anguilla', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.nic.ai', idn: false },
  me: { registry: 'domain.me (Identity Digital)', type: 'cc', country: 'Montenegro', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.nic.me', idn: true },
  tv: { registry: 'GoDaddy Registry', type: 'cc', country: 'Tuvalu', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.nic.tv', idn: true },
  cc: { registry: 'eNIC (Identity Digital)', type: 'cc', country: 'Cocos (Keeling) Islands', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.nic.cc', idn: true },
  us: { registry: 'Registry Services, LLC', type: 'cc', country: 'United States', rdap: 'https://rdap.nic.us/', whois: 'whois.nic.us', idn: false },
  ca: { registry: 'Canadian Internet Registration Authority (CIRA)', type: 'cc', country: 'Canada', rdap: 'https://rdap.cira.ca/rdap/', whois: 'whois.cira.ca', idn: false },
  uk: { registry: 'Nominet UK', type: 'cc', country: 'United Kingdom', rdap: 'https://rdap.nominet.uk/uk/', whois: 'whois.nic.uk', idn: false },
  eu: { registry: 'EURid', type: 'cc', country: 'European Union', rdap: 'https://rdap.eu/rdap/', whois: 'whois.eu', idn: true },
  de: { registry: 'DENIC eG', type: 'cc', country: 'Germany', rdap: 'https://rdap.denic.de/', whois: 'whois.denic.de', idn: true },
  fr: { registry: 'AFNIC', type: 'cc', country: 'France', rdap: 'https://rdap.nic.fr/', whois: 'whois.nic.fr', idn: true },
  nl: { registry: 'SIDN', type: 'cc', country: 'Netherlands', rdap: 'https://rdap.sidn.nl/', whois: 'whois.domain-registry.nl', idn: true },
  it: { registry: 'Registro .it (CNR)', type: 'cc', country: 'Italy', rdap: 'https://rdap.nic.it/', whois: 'whois.nic.it', idn: true },
  es: { registry: 'Red.es', type: 'cc', country: 'Spain', rdap: 'https://rdap.red.es/', whois: 'whois.nic.es', idn: true },
  pl: { registry: 'NASK', type: 'cc', country: 'Poland', rdap: 'https://rdap.dns.pl/', whois: 'whois.dns.pl', idn: true },
  se: { registry: 'The Swedish Internet Foundation', type: 'cc', country: 'Sweden', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.nic-se.se', idn: true },
  ch: { registry: 'SWITCH', type: 'cc', country: 'Switzerland', rdap: 'https://rdap.nic.ch/', whois: 'whois.nic.ch', idn: true },
  at: { registry: 'nic.at GmbH', type: 'cc', country: 'Austria', rdap: 'https://rdap.nic.at/', whois: 'whois.nic.at', idn: true },
  be: { registry: 'DNS Belgium', type: 'cc', country: 'Belgium', rdap: 'https://rdap.dnsbelgium.be/', whois: 'whois.dns.be', idn: true },
  pt: { registry: '.PT (DNS.PT)', type: 'cc', country: 'Portugal', rdap: 'https://rdap.dns.pt/', whois: 'whois.dns.pt', idn: true },
  dk: { registry: 'Punktum dk', type: 'cc', country: 'Denmark', rdap: 'https://rdap.dk-hostmaster.dk/', whois: 'whois.dk-hostmaster.dk', idn: true },
  fi: { registry: 'Traficom', type: 'cc', country: 'Finland', rdap: 'https://rdap.fi/', whois: 'whois.fi', idn: true },
  no: { registry: 'Norid AS', type: 'cc', country: 'Norway', rdap: 'https://rdap.norid.no/', whois: 'whois.norid.no', idn: true },
  is: { registry: 'ISNIC', type: 'cc', country: 'Iceland', rdap: 'https://rdap.isnic.is/', whois: 'whois.isnic.is', idn: true },
  ie: { registry: 'IEDR', type: 'cc', country: 'Ireland', rdap: 'https://rdap.iedr.ie/', whois: 'whois.iedr.ie', idn: true },
  cz: { registry: 'CZ.NIC', type: 'cc', country: 'Czechia', rdap: 'https://rdap.nic.cz/', whois: 'whois.nic.cz', idn: true },
  sk: { registry: 'SK-NIC', type: 'cc', country: 'Slovakia', rdap: 'https://rdap.sk-nic.sk/', whois: 'whois.sk-nic.sk', idn: true },
  hu: { registry: 'Council of Hungarian Internet Providers', type: 'cc', country: 'Hungary', rdap: 'https://rdap.nic.hu/', whois: 'whois.nic.hu', idn: true },
  ro: { registry: 'Rotld (ICI)', type: 'cc', country: 'Romania', rdap: 'https://rdap.rotld.ro/', whois: 'whois.rotld.ro', idn: true },
  gr: { registry: 'ICS-FORTH GR', type: 'cc', country: 'Greece', rdap: 'https://rdap.ics.forth.gr/', whois: 'whois.ics.forth.gr', idn: true },
  bg: { registry: 'Register.BG', type: 'cc', country: 'Bulgaria', rdap: 'https://rdap.register.bg/', whois: 'whois.register.bg', idn: true },
  lt: { registry: 'Kaunas University of Technology', type: 'cc', country: 'Lithuania', rdap: 'https://rdap.domreg.lt/', whois: 'whois.domreg.lt', idn: true },
  lv: { registry: 'NIC.lv (IMCS UL)', type: 'cc', country: 'Latvia', rdap: 'https://rdap.nic.lv/', whois: 'whois.nic.lv', idn: true },
  ee: { registry: 'Estonian Internet Foundation', type: 'cc', country: 'Estonia', rdap: 'https://rdap.internet.ee/', whois: 'whois.internet.ee', idn: true },
  hr: { registry: 'CARNET', type: 'cc', country: 'Croatia', rdap: 'https://rdap.dns.hr/', whois: 'whois.dns.hr', idn: true },
  si: { registry: 'ARNES', type: 'cc', country: 'Slovenia', rdap: 'https://rdap.register.si/', whois: 'whois.register.si', idn: true },
  rs: { registry: 'RNIDS', type: 'cc', country: 'Serbia', rdap: 'https://rdap.rnids.rs/', whois: 'whois.rnids.rs', idn: true },
  ua: { registry: 'Hostmaster Ltd', type: 'cc', country: 'Ukraine', rdap: 'https://rdap.hostmaster.ua/', whois: 'whois.ua', idn: true },
  ru: { registry: 'Coordination Center for TLD RU', type: 'cc', country: 'Russia', rdap: null, whois: 'whois.tcinet.ru', idn: true },
  by: { registry: 'Reliable Software Inc.', type: 'cc', country: 'Belarus', rdap: null, whois: 'whois.cctld.by', idn: false },
  tr: { registry: 'TRABIS (nic.tr)', type: 'cc', country: 'Türkiye', rdap: null, whois: 'whois.trabis.gov.tr', idn: true },
  il: { registry: 'Israel Internet Association', type: 'cc', country: 'Israel', rdap: null, whois: 'whois.isoc.org.il', idn: true },
  in: { registry: 'NIXI (registry.in)', type: 'cc', country: 'India', rdap: 'https://rdap.registry.in/', whois: 'whois.registry.in', idn: true },
  cn: { registry: 'CNNIC', type: 'cc', country: 'China', rdap: null, whois: 'whois.cnnic.cn', idn: true },
  hk: { registry: 'HKIRC', type: 'cc', country: 'Hong Kong', rdap: 'https://rdap.hkirc.hk/', whois: 'whois.hkirc.hk', idn: true },
  tw: { registry: 'TWNIC', type: 'cc', country: 'Taiwan', rdap: null, whois: 'whois.twnic.net.tw', idn: true },
  jp: { registry: 'Japan Registry Services (JPRS)', type: 'cc', country: 'Japan', rdap: 'https://rdap.jprs.jp/rdap/', whois: 'whois.jprs.jp', idn: true },
  kr: { registry: 'KISA', type: 'cc', country: 'South Korea', rdap: null, whois: 'whois.kisa.or.kr', idn: true },
  sg: { registry: 'SGNIC', type: 'cc', country: 'Singapore', rdap: null, whois: 'whois.sgnic.sg', idn: true },
  my: { registry: 'MYNIC', type: 'cc', country: 'Malaysia', rdap: null, whois: 'whois.mynic.my', idn: true },
  id: { registry: 'PANDI', type: 'cc', country: 'Indonesia', rdap: null, whois: 'whois.id', idn: true },
  th: { registry: 'THNIC', type: 'cc', country: 'Thailand', rdap: null, whois: 'whois.thnic.co.th', idn: true },
  vn: { registry: 'VNNIC', type: 'cc', country: 'Vietnam', rdap: null, whois: 'whois.vnnic.vn', idn: true },
  ph: { registry: 'dotPH', type: 'cc', country: 'Philippines', rdap: null, whois: 'whois.dot.ph', idn: false },
  pk: { registry: 'PKNIC', type: 'cc', country: 'Pakistan', rdap: null, whois: 'whois.pknic.net.pk', idn: false },
  bd: { registry: 'Bangladesh Telecommunications Company', type: 'cc', country: 'Bangladesh', rdap: null, whois: 'whois.btcl.gov.bd', idn: false },
  nz: { registry: 'InternetNZ', type: 'cc', country: 'New Zealand', rdap: 'https://rdap.internetnz.nz/', whois: 'whois.srs.net.nz', idn: false },
  au: { registry: 'auDA (.au Registry Services)', type: 'cc', country: 'Australia', rdap: 'https://rdap.auda.org.au/', whois: 'whois.auda.org.au', idn: false },
  za: { registry: 'ZACR', type: 'cc', country: 'South Africa', rdap: 'https://rdap.registry.net.za/rdap/', whois: 'whois.registry.net.za', idn: false },
  br: { registry: 'NIC.br', type: 'cc', country: 'Brazil', rdap: 'https://rdap.registro.br/', whois: 'whois.registro.br', idn: true },
  mx: { registry: 'NIC México', type: 'cc', country: 'Mexico', rdap: 'https://rdap.nic.mx/', whois: 'whois.mx', idn: false },
  ar: { registry: 'NIC Argentina', type: 'cc', country: 'Argentina', rdap: 'https://rdap.nic.ar/', whois: 'whois.nic.ar', idn: false },
  cl: { registry: 'NIC Chile', type: 'cc', country: 'Chile', rdap: null, whois: 'whois.nic.cl', idn: true },
  pe: { registry: 'Red Científica Peruana', type: 'cc', country: 'Peru', rdap: null, whois: 'kero.yachay.pe', idn: false },
  uy: { registry: 'SeCIU (Udelar)', type: 'cc', country: 'Uruguay', rdap: null, whois: 'whois.nic.org.uy', idn: false },
  ve: { registry: 'CONATEL', type: 'cc', country: 'Venezuela', rdap: null, whois: 'whois.nic.ve', idn: false },
  ae: { registry: 'TDRA (.aeDA)', type: 'cc', country: 'United Arab Emirates', rdap: null, whois: 'whois.aeda.net.ae', idn: false },
  sa: { registry: 'SaudiNIC', type: 'cc', country: 'Saudi Arabia', rdap: null, whois: 'whois.nic.net.sa', idn: true },
  eg: { registry: 'TE Data (NTRA)', type: 'cc', country: 'Egypt', rdap: null, whois: 'whois.registry.net.eg', idn: false },
  ng: { registry: 'NIRA', type: 'cc', country: 'Nigeria', rdap: null, whois: 'whois.nic.net.ng', idn: false },
  ke: { registry: 'KeNIC', type: 'cc', country: 'Kenya', rdap: null, whois: 'whois.kenic.or.ke', idn: false },
  ge: { registry: 'Caucasus Online', type: 'cc', country: 'Georgia', rdap: null, whois: 'whois.nic.ge', idn: true },
  kz: { registry: 'KazNIC', type: 'cc', country: 'Kazakhstan', rdap: null, whois: 'whois.nic.kz', idn: true },
  az: { registry: 'IntraNS', type: 'cc', country: 'Azerbaijan', rdap: null, whois: 'whois.az', idn: false },
  am: { registry: 'AMNIC (ISOC AM)', type: 'cc', country: 'Armenia', rdap: null, whois: 'whois.amnic.net', idn: false },
  md: { registry: 'MoldData', type: 'cc', country: 'Moldova', rdap: null, whois: 'whois.nic.md', idn: false },
  ir: { registry: 'IPM (IRNIC)', type: 'cc', country: 'Iran', rdap: null, whois: 'whois.nic.ir', idn: true },
  iq: { registry: 'CMC (NIC.iq)', type: 'cc', country: 'Iraq', rdap: null, whois: 'whois.cmc.iq', idn: false },
  qa: { registry: 'CRA Qatar', type: 'cc', country: 'Qatar', rdap: null, whois: 'whois.registry.qa', idn: false },
  kw: { registry: 'CITRA', type: 'cc', country: 'Kuwait', rdap: null, whois: 'whois.nic.kw', idn: false },
  bh: { registry: 'TRA Bahrain', type: 'cc', country: 'Bahrain', rdap: null, whois: 'whois.nic.bh', idn: false },
  om: { registry: 'TRA Oman', type: 'cc', country: 'Oman', rdap: null, whois: 'whois.registry.om', idn: false },
  jo: { registry: 'NITC Jordan', type: 'cc', country: 'Jordan', rdap: null, whois: 'whois.dns.jo', idn: false },
  lb: { registry: 'LBDR (AUB)', type: 'cc', country: 'Lebanon', rdap: null, whois: 'whois.lbdr.org.lb', idn: false },
  ma: { registry: 'ANRT', type: 'cc', country: 'Morocco', rdap: null, whois: 'whois.registre.ma', idn: false },
  tn: { registry: 'ATI (Tunisia)', type: 'cc', country: 'Tunisia', rdap: null, whois: 'whois.ati.tn', idn: false },
  dz: { registry: 'CERIST (NIC.dz)', type: 'cc', country: 'Algeria', rdap: null, whois: 'whois.nic.dz', idn: false },
  gh: { registry: 'Ghana Dot Com (NITA)', type: 'cc', country: 'Ghana', rdap: null, whois: 'whois.nic.gh', idn: false },
  tz: { registry: 'tzNIC', type: 'cc', country: 'Tanzania', rdap: null, whois: 'whois.tznic.or.tz', idn: false },
  ug: { registry: 'Uganda Registry', type: 'cc', country: 'Uganda', rdap: null, whois: 'whois.co.ug', idn: false },
  ci: { registry: 'ART-CI (NIC.ci)', type: 'cc', country: "Côte d'Ivoire", rdap: null, whois: 'whois.nic.ci', idn: false },
  sn: { registry: 'NIC Senegal', type: 'cc', country: 'Senegal', rdap: null, whois: 'whois.nic.sn', idn: false },
  cm: { registry: 'ANTIC', type: 'cc', country: 'Cameroon', rdap: null, whois: 'whois.netcom.cm', idn: false },
  mu: { registry: 'NIC.mu', type: 'cc', country: 'Mauritius', rdap: null, whois: 'whois.nic.mu', idn: false },
  na: { registry: 'Namibian Network Information Centre', type: 'cc', country: 'Namibia', rdap: null, whois: 'whois.na-nic.com.na', idn: false },
  bw: { registry: 'BOCRA', type: 'cc', country: 'Botswana', rdap: null, whois: 'whois.nic.net.bw', idn: false },
  zw: { registry: 'ZISPA', type: 'cc', country: 'Zimbabwe', rdap: null, whois: 'whois.zispa.org.zw', idn: false },
  zm: { registry: 'ZICTA', type: 'cc', country: 'Zambia', rdap: null, whois: 'whois.zicta.zm', idn: false },
  mw: { registry: 'MACRA', type: 'cc', country: 'Malawi', rdap: null, whois: 'whois.nic.mw', idn: false },
  et: { registry: 'Ethio Telecom', type: 'cc', country: 'Ethiopia', rdap: null, whois: 'whois.ethiotelecom.et', idn: false },
  so: { registry: 'SONIC (NIC.so)', type: 'cc', country: 'Somalia', rdap: null, whois: 'whois.nic.so', idn: false },
  ly: { registry: 'LTT (NIC.ly)', type: 'cc', country: 'Libya', rdap: null, whois: 'whois.nic.ly', idn: false },
  sd: { registry: 'Sudan Internet Society', type: 'cc', country: 'Sudan', rdap: null, whois: 'whois.isoc.sd', idn: false },
  gg: { registry: 'Island Networks', type: 'cc', country: 'Guernsey', rdap: 'https://rdap.channelisles.net/', whois: 'whois.gg', idn: false },
  je: { registry: 'Island Networks', type: 'cc', country: 'Jersey', rdap: 'https://rdap.channelisles.net/', whois: 'whois.je', idn: false },
  im: { registry: 'Isle of Man Government', type: 'cc', country: 'Isle of Man', rdap: null, whois: 'whois.nic.im', idn: false },
  fm: { registry: 'BRS Media (dotFM)', type: 'cc', country: 'Micronesia', rdap: null, whois: 'whois.nic.fm', idn: false },
  to: { registry: 'Tonga Network Information Center', type: 'cc', country: 'Tonga', rdap: null, whois: 'whois.tonic.to', idn: false },
  ws: { registry: 'SamoaNIC', type: 'cc', country: 'Samoa', rdap: null, whois: 'whois.samoanic.ws', idn: false },
  nu: { registry: 'Internet Foundation in Sweden', type: 'cc', country: 'Niue', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.iis.nu', idn: true },
  sh: { registry: 'NIC.SH (Identity Digital)', type: 'cc', country: 'Saint Helena', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.nic.sh', idn: true },
  ac: { registry: 'NIC.AC (Identity Digital)', type: 'cc', country: 'Ascension Island', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.nic.ac', idn: true },
  gl: { registry: 'TELE Greenland', type: 'cc', country: 'Greenland', rdap: null, whois: 'whois.nic.gl', idn: false },
  ky: { registry: 'Cayman Islands ICTA', type: 'cc', country: 'Cayman Islands', rdap: null, whois: 'whois.kyregistry.ky', idn: false },
  vg: { registry: 'TRC BVI', type: 'cc', country: 'British Virgin Islands', rdap: null, whois: 'whois.adamsnames.tc', idn: false },
  ag: { registry: 'UHSA Antigua', type: 'cc', country: 'Antigua and Barbuda', rdap: null, whois: 'whois.nic.ag', idn: false },
  dm: { registry: 'DotDM Corporation', type: 'cc', country: 'Dominica', rdap: null, whois: 'whois.nic.dm', idn: false },
  gd: { registry: 'Grenada NIC', type: 'cc', country: 'Grenada', rdap: null, whois: 'whois.nic.gd', idn: false },
  kn: { registry: 'St. Kitts & Nevis NIC', type: 'cc', country: 'Saint Kitts and Nevis', rdap: null, whois: 'whois.nic.kn', idn: false },
  lc: { registry: 'NIC.LC', type: 'cc', country: 'Saint Lucia', rdap: null, whois: 'whois.nic.lc', idn: false },
  vc: { registry: 'NIC.VC', type: 'cc', country: 'Saint Vincent and the Grenadines', rdap: null, whois: 'whois.nic.vc', idn: false },
  bz: { registry: 'BelizeNIC', type: 'cc', country: 'Belize', rdap: null, whois: 'whois.afilias-grs.info', idn: false },
  hn: { registry: 'Red de Desarrollo Sostenible', type: 'cc', country: 'Honduras', rdap: null, whois: 'whois.nic.hn', idn: false },
  pa: { registry: 'NIC Panamá', type: 'cc', country: 'Panama', rdap: null, whois: 'whois.nic.pa', idn: false },
  do: { registry: 'NIC.do', type: 'cc', country: 'Dominican Republic', rdap: null, whois: 'whois.nic.do', idn: false },
  cr: { registry: 'NIC Costa Rica', type: 'cc', country: 'Costa Rica', rdap: null, whois: 'whois.nic.cr', idn: false },
  pr: { registry: 'Gauss Research Laboratory', type: 'cc', country: 'Puerto Rico', rdap: null, whois: 'whois.nic.pr', idn: false },
  tt: { registry: 'TTNIC (UWI)', type: 'cc', country: 'Trinidad and Tobago', rdap: null, whois: 'whois.nic.tt', idn: false },
  jm: { registry: 'Mona Information Technology Services', type: 'cc', country: 'Jamaica', rdap: null, whois: 'whois.nic.jm', idn: false },
  ba: { registry: 'UTIC', type: 'cc', country: 'Bosnia and Herzegovina', rdap: null, whois: 'whois.nic.ba', idn: false },
  mk: { registry: 'MARNAT', type: 'cc', country: 'North Macedonia', rdap: null, whois: 'whois.marnet.mk', idn: false },
  me2: null, // guard against accidental duplicates below
  al: { registry: 'AKEP', type: 'cc', country: 'Albania', rdap: null, whois: 'whois.akep.al', idn: false },
  xk: { registry: 'Kosovo (unofficial)', type: 'cc', country: 'Kosovo', rdap: null, whois: null, idn: false },

  cy: { registry: 'University of Cyprus', type: 'cc', country: 'Cyprus', rdap: null, whois: 'whois.nic.cy', idn: false },
  mt: { registry: 'NIC Malta', type: 'cc', country: 'Malta', rdap: null, whois: 'whois.nic.org.mt', idn: false },

  li: { registry: 'SWITCH (NIC.li)', type: 'cc', country: 'Liechtenstein', rdap: null, whois: 'whois.nic.li', idn: true },
  lu: { registry: 'RESTENA', type: 'cc', country: 'Luxembourg', rdap: 'https://rdap.dns.lu/', whois: 'whois.dns.lu', idn: false },
  mc: { registry: 'Gouvernement de Monaco', type: 'cc', country: 'Monaco', rdap: null, whois: 'whois.nic.mc', idn: false },
  sm: { registry: 'Telecom Italia San Marino', type: 'cc', country: 'San Marino', rdap: null, whois: 'whois.nic.sm', idn: false },
  va: { registry: 'Holy See', type: 'cc', country: 'Vatican City', rdap: null, whois: 'whois.iana.org', idn: false },
  ad: { registry: 'Andorra Telecom', type: 'cc', country: 'Andorra', rdap: null, whois: 'whois.nic.ad', idn: false },
  gi: { registry: 'Gibraltar Regulatory Authority', type: 'cc', country: 'Gibraltar', rdap: null, whois: 'whois.identitydigital.services', idn: false },
  mo: { registry: 'MONIC', type: 'cc', country: 'Macao', rdap: null, whois: 'whois.monic.mo', idn: true },
  mn: { registry: 'Datacom', type: 'cc', country: 'Mongolia', rdap: null, whois: 'whois.nic.mn', idn: true },
  kh: { registry: 'MPTC', type: 'cc', country: 'Cambodia', rdap: null, whois: 'whois.nic.net.kh', idn: false },
  la: { registry: 'LANIC', type: 'cc', country: 'Laos', rdap: null, whois: 'whois.nic.la', idn: false },
  mm: { registry: 'MMNIC', type: 'cc', country: 'Myanmar', rdap: null, whois: 'whois.registry.gov.mm', idn: false },
  lk: { registry: 'LK Domain Registry', type: 'cc', country: 'Sri Lanka', rdap: null, whois: 'whois.nic.lk', idn: true },
  np: { registry: 'Mercantile Communications', type: 'cc', country: 'Nepal', rdap: null, whois: 'whois.nic.net.np', idn: false },
  bt: { registry: 'Bhutan Telecom', type: 'cc', country: 'Bhutan', rdap: null, whois: 'whois.nic.bt', idn: false },
  mv: { registry: 'Dhiraagu', type: 'cc', country: 'Maldives', rdap: null, whois: 'whois.nic.mv', idn: false },
  af: { registry: 'AFGNIC', type: 'cc', country: 'Afghanistan', rdap: null, whois: 'whois.nic.af', idn: false },
  uz: { registry: 'UZINFOCOM', type: 'cc', country: 'Uzbekistan', rdap: null, whois: 'whois.cctld.uz', idn: false },
  kg: { registry: 'AsiaInfo', type: 'cc', country: 'Kyrgyzstan', rdap: null, whois: 'whois.kg', idn: false },
  tj: { registry: 'Information Technology Center', type: 'cc', country: 'Tajikistan', rdap: null, whois: 'whois.nic.tj', idn: false },
  tm: { registry: 'TM Domain Registry', type: 'cc', country: 'Turkmenistan', rdap: null, whois: 'whois.nic.tm', idn: false },
  edu: { registry: 'EDUCAUSE', type: 'g', rdap: null, whois: 'whois.educause.edu', idn: false },
  gov: { registry: 'Cybersecurity and Infrastructure Security Agency', type: 'g', rdap: null, whois: 'whois.nic.gov', idn: false },
  mil: { registry: 'US Department of Defense', type: 'g', rdap: null, whois: 'whois.nic.mil', idn: false },
  int: { registry: 'IANA', type: 'g', rdap: null, whois: 'whois.iana.org', idn: false },
  aero: { registry: 'SITA', type: 'g', rdap: null, whois: 'whois.aero', idn: false },
  coop: { registry: 'DotCooperation', type: 'g', rdap: null, whois: 'whois.nic.coop', idn: false },
  museum: { registry: 'Museum Domain Management Association', type: 'g', rdap: null, whois: 'whois.nic.museum', idn: true },
  tel: { registry: 'Telnames', type: 'g', rdap: null, whois: 'whois.nic.tel', idn: false },
  travel: { registry: 'Donuts (Travel)', type: 'g', rdap: null, whois: 'whois.nic.travel', idn: false },
  cat: { registry: 'Fundació puntCAT', type: 'g', rdap: null, whois: 'whois.nic.cat', idn: true },
  jobs: { registry: 'Employ Media', type: 'g', rdap: null, whois: 'whois.nic.jobs', idn: false },
  post: { registry: 'Universal Postal Union', type: 'g', rdap: null, whois: 'whois.afilias.info', idn: false },
  xxx: { registry: 'ICM Registry', type: 'g', rdap: null, whois: 'whois.nic.xxx', idn: false },

  sbs: { registry: 'ShortDot SA', type: 'g', rdap: 'https://rdap.centralnic.com/sbs/', whois: 'whois.nic.sbs', idn: true },
  icu: { registry: 'ShortDot SA', type: 'g', rdap: 'https://rdap.centralnic.com/icu/', whois: 'whois.nic.icu', idn: true },
  bond: { registry: 'ShortDot SA', type: 'g', rdap: 'https://rdap.centralnic.com/bond/', whois: 'whois.nic.bond', idn: true },
  cyou: { registry: 'ShortDot SA', type: 'g', rdap: 'https://rdap.centralnic.com/cyou/', whois: 'whois.nic.cyou', idn: true },
  cfd: { registry: 'ShortDot SA', type: 'g', rdap: 'https://rdap.centralnic.com/cfd/', whois: 'whois.nic.cfd', idn: true },
  fun: { registry: 'Radix', type: 'g', rdap: 'https://rdap.centralnic.com/fun/', whois: 'whois.nic.fun', idn: true },
  host: { registry: 'Radix', type: 'g', rdap: 'https://rdap.centralnic.com/host/', whois: 'whois.nic.host', idn: true },
  press: { registry: 'Radix', type: 'g', rdap: 'https://rdap.centralnic.com/press/', whois: 'whois.nic.press', idn: true },
  space: { registry: 'Radix', type: 'g', rdap: 'https://rdap.centralnic.com/space/', whois: 'whois.nic.space', idn: true },
  website: { registry: 'Radix', type: 'g', rdap: 'https://rdap.centralnic.com/website/', whois: 'whois.nic.website', idn: true },
  pw: { registry: 'Radix (NIC.PW)', type: 'cc', country: 'Palau', rdap: 'https://rdap.centralnic.com/pw/', whois: 'whois.nic.pw', idn: true },
  top: { registry: 'Jiangsu Bangning Science & Technology', type: 'g', rdap: 'https://rdap.centralnic.com/top/', whois: 'whois.nic.top', idn: true },
  vip: { registry: 'Minds + Machines', type: 'g', rdap: 'https://rdap.mm-registry.com/', whois: 'whois.mm-registry.com', idn: true },
  fit: { registry: 'Minds + Machines', type: 'g', rdap: 'https://rdap.mm-registry.com/', whois: 'whois.mm-registry.com', idn: true },
  lol: { registry: 'XYZ.com LLC', type: 'g', rdap: 'https://rdap.centralnic.com/lol/', whois: 'whois.nic.lol', idn: true },
  live: { registry: 'Identity Digital', type: 'g', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.identitydigital.services', idn: true },
  life: { registry: 'Identity Digital', type: 'g', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.identitydigital.services', idn: true },
  world: { registry: 'Identity Digital', type: 'g', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.identitydigital.services', idn: true },
  today: { registry: 'Identity Digital', type: 'g', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.identitydigital.services', idn: true },
  company: { registry: 'Identity Digital', type: 'g', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.identitydigital.services', idn: true },
  solutions: { registry: 'Identity Digital', type: 'g', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.identitydigital.services', idn: true },
  network: { registry: 'Identity Digital', type: 'g', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.identitydigital.services', idn: true },
  group: { registry: 'Identity Digital', type: 'g', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.identitydigital.services', idn: true },
  agency: { registry: 'Identity Digital', type: 'g', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.identitydigital.services', idn: true },
  email: { registry: 'Identity Digital', type: 'g', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.identitydigital.services', idn: true },
  services: { registry: 'Identity Digital', type: 'g', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.identitydigital.services', idn: true },
  ninja: { registry: 'Identity Digital', type: 'g', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.identitydigital.services', idn: true },
  guru: { registry: 'Identity Digital', type: 'g', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.identitydigital.services', idn: true },
  link: { registry: 'Nova Registry', type: 'g', rdap: 'https://rdap.uniregistry.net/', whois: 'whois.uniregistry.net', idn: true },
  click: { registry: 'Nova Registry', type: 'g', rdap: 'https://rdap.uniregistry.net/', whois: 'whois.uniregistry.net', idn: true },
  country: { registry: 'Nova Registry', type: 'g', rdap: 'https://rdap.uniregistry.net/', whois: 'whois.uniregistry.net', idn: true },
  help: { registry: 'Nova Registry', type: 'g', rdap: 'https://rdap.uniregistry.net/', whois: 'whois.uniregistry.net', idn: true },
  property: { registry: 'Nova Registry', type: 'g', rdap: 'https://rdap.uniregistry.net/', whois: 'whois.uniregistry.net', idn: true },
  loan: { registry: 'Nova Registry', type: 'g', rdap: 'https://rdap.uniregistry.net/', whois: 'whois.uniregistry.net', idn: true },
  men: { registry: 'Nova Registry', type: 'g', rdap: 'https://rdap.uniregistry.net/', whois: 'whois.uniregistry.net', idn: true },
  win: { registry: 'Nova Registry', type: 'g', rdap: 'https://rdap.uniregistry.net/', whois: 'whois.uniregistry.net', idn: true },
  bid: { registry: 'Nova Registry', type: 'g', rdap: 'https://rdap.uniregistry.net/', whois: 'whois.uniregistry.net', idn: true },
  trade: { registry: 'Nova Registry', type: 'g', rdap: 'https://rdap.uniregistry.net/', whois: 'whois.uniregistry.net', idn: true },
  date: { registry: 'Nova Registry', type: 'g', rdap: 'https://rdap.uniregistry.net/', whois: 'whois.uniregistry.net', idn: true },
  download: { registry: 'Nova Registry', type: 'g', rdap: 'https://rdap.uniregistry.net/', whois: 'whois.uniregistry.net', idn: true },
  racing: { registry: 'Nova Registry', type: 'g', rdap: 'https://rdap.uniregistry.net/', whois: 'whois.uniregistry.net', idn: true },
  review: { registry: 'Nova Registry', type: 'g', rdap: 'https://rdap.uniregistry.net/', whois: 'whois.uniregistry.net', idn: true },
  stream: { registry: 'Nova Registry', type: 'g', rdap: 'https://rdap.uniregistry.net/', whois: 'whois.uniregistry.net', idn: true },
  accountants: { registry: 'Nova Registry', type: 'g', rdap: 'https://rdap.uniregistry.net/', whois: 'whois.uniregistry.net', idn: true },
  party: { registry: 'Nova Registry', type: 'g', rdap: 'https://rdap.uniregistry.net/', whois: 'whois.uniregistry.net', idn: true },
  faith: { registry: 'Nova Registry', type: 'g', rdap: 'https://rdap.uniregistry.net/', whois: 'whois.uniregistry.net', idn: true },
  ooo: { registry: 'XYZ.com LLC', type: 'g', rdap: 'https://rdap.centralnic.com/ooo/', whois: 'whois.nic.ooo', idn: true },
  monster: { registry: 'XYZ.com LLC', type: 'g', rdap: 'https://rdap.centralnic.com/monster/', whois: 'whois.nic.monster', idn: true },
  quest: { registry: 'XYZ.com LLC', type: 'g', rdap: 'https://rdap.centralnic.com/quest/', whois: 'whois.nic.quest', idn: true },
  baby: { registry: 'XYZ.com LLC', type: 'g', rdap: 'https://rdap.centralnic.com/baby/', whois: 'whois.nic.baby', idn: true },
  beauty: { registry: 'XYZ.com LLC', type: 'g', rdap: 'https://rdap.centralnic.com/beauty/', whois: 'whois.nic.beauty', idn: true },
  hair: { registry: 'XYZ.com LLC', type: 'g', rdap: 'https://rdap.centralnic.com/hair/', whois: 'whois.nic.hair', idn: true },

  wiki: { registry: 'Top Level Design', type: 'g', rdap: 'https://rdap.centralnic.com/wiki/', whois: 'whois.nic.wiki', idn: true },
  ink: { registry: 'Top Level Design', type: 'g', rdap: 'https://rdap.centralnic.com/ink/', whois: 'whois.nic.ink', idn: true },
  gay: { registry: 'Top Level Design', type: 'g', rdap: 'https://rdap.centralnic.com/gay/', whois: 'whois.nic.gay', idn: true },
  one: { registry: 'One Registry', type: 'g', rdap: 'https://rdap.centralnic.com/one/', whois: 'whois.nic.one', idn: true },
  art: { registry: 'UK Creative Ideas', type: 'g', rdap: 'https://rdap.centralnic.com/art/', whois: 'whois.nic.art', idn: true },
  bio: { registry: 'Identity Digital', type: 'g', rdap: 'https://rdap.identitydigital.services/rdap/', whois: 'whois.identitydigital.services', idn: true },
  city: { registry: 'Snow City LLC', type: 'g', rdap: 'https://rdap.centralnic.com/city/', whois: 'whois.nic.city', idn: true },
  realty: { registry: 'Fegistry', type: 'g', rdap: 'https://rdap.centralnic.com/realty/', whois: 'whois.nic.realty', idn: true },

  yt: { registry: 'AFNIC (NIC.yt)', type: 'cc', country: 'Mayotte', rdap: 'https://rdap.nic.fr/', whois: 'whois.nic.yt', idn: true },
  pm: { registry: 'AFNIC (NIC.pm)', type: 'cc', country: 'Saint Pierre and Miquelon', rdap: 'https://rdap.nic.fr/', whois: 'whois.nic.pm', idn: true },
  re: { registry: 'AFNIC (NIC.re)', type: 'cc', country: 'Réunion', rdap: 'https://rdap.nic.fr/', whois: 'whois.nic.re', idn: true },
  tf: { registry: 'AFNIC (NIC.tf)', type: 'cc', country: 'French Southern Territories', rdap: 'https://rdap.nic.fr/', whois: 'whois.nic.tf', idn: true },
  wf: { registry: 'AFNIC (NIC.wf)', type: 'cc', country: 'Wallis and Futuna', rdap: 'https://rdap.nic.fr/', whois: 'whois.nic.wf', idn: true },
  su: { registry: 'Russian Institute for Public Networks', type: 'cc', country: 'Soviet Union (legacy)', rdap: null, whois: 'whois.tcinet.ru', idn: true },
  ps: { registry: 'PNINA', type: 'cc', country: 'Palestine', rdap: null, whois: 'whois.pnina.ps', idn: false },
  sy: { registry: 'NANS', type: 'cc', country: 'Syria', rdap: null, whois: 'whois.tld.sy', idn: false },
  ye: { registry: 'TeleYemen', type: 'cc', country: 'Yemen', rdap: null, whois: 'whois.y.net.ye', idn: false },
  mz: { registry: 'CIUEM', type: 'cc', country: 'Mozambique', rdap: null, whois: 'whois.nic.mz', idn: false },
  ao: { registry: 'Universidade Agostinho Neto', type: 'cc', country: 'Angola', rdap: null, whois: 'whois.dns.ao', idn: false },
  cd: { registry: 'Office Congolais des Postes', type: 'cc', country: 'DR Congo', rdap: null, whois: 'whois.nic.cd', idn: false },
  gm: { registry: 'GMNO', type: 'cc', country: 'Gambia', rdap: null, whois: 'whois.nic.gm', idn: false },
  sl: { registry: 'Sierra Leone', type: 'cc', country: 'Sierra Leone', rdap: null, whois: 'whois.nic.sl', idn: false },
  lr: { registry: 'Liberia', type: 'cc', country: 'Liberia', rdap: null, whois: null, idn: false },
  td: { registry: 'NIC.td', type: 'cc', country: 'Chad', rdap: null, whois: 'whois.nic.td', idn: false },
  ga: { registry: 'ANINF', type: 'cc', country: 'Gabon', rdap: null, whois: 'whois.nic.ga', idn: false },
  gq: { registry: 'GETESA', type: 'cc', country: 'Equatorial Guinea', rdap: null, whois: null, idn: false },
  cg: { registry: 'ONPT', type: 'cc', country: 'Republic of the Congo', rdap: null, whois: null, idn: false },
  bj: { registry: 'Benin NIC', type: 'cc', country: 'Benin', rdap: null, whois: null, idn: false },
  tg: { registry: 'Cafe Informatique', type: 'cc', country: 'Togo', rdap: null, whois: 'whois.nic.tg', idn: false },
  ml: { registry: 'AGETIC', type: 'cc', country: 'Mali', rdap: null, whois: null, idn: false },
  bf: { registry: 'ARTEL', type: 'cc', country: 'Burkina Faso', rdap: null, whois: null, idn: false },
  ne: { registry: 'SONITEL', type: 'cc', country: 'Niger', rdap: null, whois: null, idn: false },
  mr: { registry: 'NIC Mauritanie', type: 'cc', country: 'Mauritania', rdap: null, whois: 'whois.nic.mr', idn: false },
  gn: { registry: 'PSGnet', type: 'cc', country: 'Guinea', rdap: null, whois: 'whois.nic.gn', idn: false },
  gw: { registry: 'NIC.GW', type: 'cc', country: 'Guinea-Bissau', rdap: null, whois: null, idn: false },
  cv: { registry: 'ANAC', type: 'cc', country: 'Cabo Verde', rdap: null, whois: 'whois.nic.cv', idn: false },
  st: { registry: 'NIC.ST', type: 'cc', country: 'São Tomé and Príncipe', rdap: null, whois: 'whois.nic.st', idn: false },
  dj: { registry: 'Djibouti Telecom', type: 'cc', country: 'Djibouti', rdap: null, whois: null, idn: false },
  er: { registry: 'Eritrea', type: 'cc', country: 'Eritrea', rdap: null, whois: null, idn: false },
  bi: { registry: 'ARCT', type: 'cc', country: 'Burundi', rdap: null, whois: null, idn: false },
  rw: { registry: 'RURA', type: 'cc', country: 'Rwanda', rdap: null, whois: null, idn: false },
  ss: { registry: 'South Sudan', type: 'cc', country: 'South Sudan', rdap: null, whois: null, idn: false },
  sc: { registry: 'NIC.SC', type: 'cc', country: 'Seychelles', rdap: null, whois: 'whois.nic.sc', idn: false },
  ls: { registry: 'LSNIC', type: 'cc', country: 'Lesotho', rdap: null, whois: null, idn: false },
  sz: { registry: 'SISPA', type: 'cc', country: 'Eswatini', rdap: null, whois: null, idn: false },
  mg: { registry: 'NIC-MG', type: 'cc', country: 'Madagascar', rdap: null, whois: 'whois.nic.mg', idn: false },
  km: { registry: 'Comoros Telecom', type: 'cc', country: 'Comoros', rdap: null, whois: null, idn: false },
  ck: { registry: 'Telecom Cook Islands', type: 'cc', country: 'Cook Islands', rdap: null, whois: 'whois.ck-nic.org.ck', idn: false },
  fk: { registry: 'Falkland Islands', type: 'cc', country: 'Falkland Islands', rdap: null, whois: null, idn: false },
  ki: { registry: 'NIC.KI', type: 'cc', country: 'Kiribati', rdap: null, whois: null, idn: false },
  nr: { registry: 'CENPACNET', type: 'cc', country: 'Nauru', rdap: null, whois: null, idn: false },
  mh: { registry: 'NIC.MH', type: 'cc', country: 'Marshall Islands', rdap: null, whois: null, idn: false },

  gf: { registry: 'AFNIC (NIC.gf)', type: 'cc', country: 'French Guiana', rdap: 'https://rdap.nic.fr/', whois: 'whois.nic.gf', idn: true },
  gp: { registry: 'AFNIC (NIC.gp)', type: 'cc', country: 'Guadeloupe', rdap: 'https://rdap.nic.fr/', whois: 'whois.nic.gp', idn: true },
  mq: { registry: 'AFNIC (NIC.mq)', type: 'cc', country: 'Martinique', rdap: 'https://rdap.nic.fr/', whois: 'whois.nic.mq', idn: true },
  nc: { registry: 'OPT.nc', type: 'cc', country: 'New Caledonia', rdap: null, whois: 'whois.nc', idn: false },
  pf: { registry: 'OPT.pf', type: 'cc', country: 'French Polynesia', rdap: null, whois: null, idn: false },
  as: { registry: 'AS Domain Registry', type: 'cc', country: 'American Samoa', rdap: null, whois: 'whois.nic.as', idn: false },
  gu: { registry: 'NIC.GU', type: 'cc', country: 'Guam', rdap: null, whois: null, idn: false },
  mp: { registry: 'Saipan DataCom', type: 'cc', country: 'Northern Mariana Islands', rdap: null, whois: null, idn: false },
  vu: { registry: 'Telecom Vanuatu', type: 'cc', country: 'Vanuatu', rdap: null, whois: null, idn: false },
  sb: { registry: 'SBTC', type: 'cc', country: 'Solomon Islands', rdap: null, whois: null, idn: false },
  fj: { registry: 'USP', type: 'cc', country: 'Fiji', rdap: null, whois: 'whois.usp.ac.fj', idn: false },
  pg: { registry: 'PNG NIC', type: 'cc', country: 'Papua New Guinea', rdap: null, whois: null, idn: false },

  aq: { registry: 'Antarctica', type: 'cc', country: 'Antarctica', rdap: null, whois: null, idn: false },
  ax: { registry: 'Ålands landskapsregering', type: 'cc', country: 'Åland Islands', rdap: null, whois: 'whois.ax', idn: false },
  bm: { registry: 'Registry General Bermuda', type: 'cc', country: 'Bermuda', rdap: null, whois: 'whois.nic.bm', idn: false },
  gs: { registry: 'Atlantis North', type: 'cc', country: 'South Georgia', rdap: null, whois: null, idn: false },
  tc: { registry: 'NIC.TC', type: 'cc', country: 'Turks and Caicos Islands', rdap: null, whois: 'whois.nic.tc', idn: false },
  ms: { registry: 'MNI Networks', type: 'cc', country: 'Montserrat', rdap: null, whois: 'whois.nic.ms', idn: false },
  aw: { registry: 'SETAR', type: 'cc', country: 'Aruba', rdap: null, whois: 'whois.setar.aw', idn: false },
  cw: { registry: 'UNA', type: 'cc', country: 'Curaçao', rdap: null, whois: null, idn: false },
  sx: { registry: 'SX Registry', type: 'cc', country: 'Sint Maarten', rdap: null, whois: null, idn: false },
  bq: { registry: 'BQ Registry', type: 'cc', country: 'Bonaire', rdap: null, whois: null, idn: false },
  mf: { registry: 'AFNIC (NIC.mf)', type: 'cc', country: 'Saint Martin', rdap: 'https://rdap.nic.fr/', whois: null, idn: true },
  bl: { registry: 'AFNIC (NIC.bl)', type: 'cc', country: 'Saint Barthélemy', rdap: 'https://rdap.nic.fr/', whois: null, idn: true },
  hm: { registry: 'HMD Registry', type: 'cc', country: 'Heard Island', rdap: null, whois: null, idn: false },
  bv: { registry: 'Norid', type: 'cc', country: 'Bouvet Island', rdap: null, whois: null, idn: false },
  sj: { registry: 'Norid', type: 'cc', country: 'Svalbard and Jan Mayen', rdap: null, whois: null, idn: false },

  cx: { registry: 'Christmas Island Domain Administration', type: 'cc', country: 'Christmas Island', rdap: null, whois: 'whois.nic.cx', idn: false },
  nf: { registry: 'NIC.NF', type: 'cc', country: 'Norfolk Island', rdap: null, whois: null, idn: false },
  tk: { registry: 'BV Dot TK', type: 'cc', country: 'Tokelau', rdap: null, whois: 'whois.dot.tk', idn: false },
  cf: { registry: 'SOCATEL', type: 'cc', country: 'Central African Republic', rdap: null, whois: 'whois.dot.cf', idn: false },
  gyt: null
};

function analyzeTld(tldLabel, fullSuffix) {
  const label = String(tldLabel || '').toLowerCase().replace(/^\./, '');
  const entry = T[label];
  if (!entry) {
    return {
      suffix: fullSuffix,
      lastLabel: label,
      known: false,
      registry: null,
      type: 'unknown',
      country: null,
      rdapEndpoint: null,
      whoisServer: null,
      idn: null,
      source: 'local-database',
      note: 'This TLD is not in the local registry database. Registry details are not shown rather than guessed.'
    };
  }
  return {
    suffix: fullSuffix,
    lastLabel: label,
    known: true,
    registry: entry.registry,
    type: entry.type === 'g' ? 'gTLD' : 'ccTLD',
    country: entry.country || null,
    rdapEndpoint: entry.rdap || null,
    whoisServer: entry.whois || null,
    idn: entry.idn == null ? null : !!entry.idn,
    source: 'local-database',
    note: entry.rdap ? null : 'This registry has no public RDAP service in the local database; the WHOIS fallback applies.'
  };
}

module.exports = { analyzeTld, TLD_DB: T };
